/* eslint-disable import/prefer-default-export */
export enum RESPONSE_TYPES {
    SERVER_ERROR = 'SERVER_ERROR',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNABLE_TO_CREATE_USER = 'UNABLE_TO_CREATE_USER',
    UNABLE_TO_LOGIN = 'UNABLE_TO_LOGIN_USER',
    UNABLE_TO_FETCH_USER = 'UNABLE_TO_FETCH_USER',
    UNABLE_TO_UPDATE_PROFILE = 'UNABLE_TO_UPDATE_PROFILE',
    FORBIDDEN = 'FORBIDDEN',
    UNABLE_TO_DELETE_USER = 'UNABLE_TO_DELETE_USER',
    UNABLE_TO_UPLOAD_AVATAR = 'UNABLE_TO_UPLOAD_AVATAR'
}
